name: Tests

on:
  push:
    branches:
      - main
      - support/*
  pull_request:

jobs:
  tests:

    strategy:
      fail-fast: false  # continue other tests if one test in matrix fails
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: Test kit on Node v${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    env:
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
    - run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0

    - name: Use Node v${{ matrix.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}

    - name: Cache Cypress binary
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

    - run: npm ci

    - run: npm run test:unit && npm run test:integration
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
